coslr: true
criterions:
  PerformanceLoss:
    def_file: SoftmaxLoss
    loss_params: {}
    optim_params: null
    weight: 1.0
endlr: 0.0
last: false
memory: {centroids: false, init_centroids: false}
networks:
  classifier:
    def_file: TauNormClassifier
    optim_params: {lr: 0.1, momentum: 0.9, weight_decay: 0.0005}
    params: {feat_dim: 2048, num_classes: 365, stage1_weights: false}
  feat_model:
    def_file: ResNet152Feature
    fix: true
    optim_params: {lr: 0.01, momentum: 0.9, weight_decay: 0.0005}
    params: {dropout: null, stage1_weights: false, use_fc: false, use_selfatt: false}
shuffle: true
training_opt:
  batch_size: 256
  display_step: 10
  feature_dim: 2048
  num_classes: 365
  num_epochs: 5
  num_workers: 4
  open_threshold: 0.1
  sampler: {num_samples_cls: 4, type: ClassAwareSampler}
  scheduler_params: {gamma: 0.1, step_size: 30}
  stage: lws_uni2ban
  sub_dir: clslearn
