## For Training
# ======= actual arguments ========
# Indexing parameters
nr_splits: 32
max_leaf_size: 100
spherical: True
kmeans_max_iter: 20
threads: -1
rel_norm: no_norm
rel_mode: disable
# Linear matching/ranking parameters
solver_type: L2R_L2LOSS_SVC_DUAL
Cp: 1.0
Cn: 1.0
bias: 1.0
negative_sampling: man
threshold: 0.1
max_nonzeros_per_label: 0
## For Predicting
max_pred_chunk: 1.0e+7