im_class_num: 3
im_ratio: 1
layer: gcn
lr: 0.001
dropout: 0.5
rw: 0.000001
ep_pre: 0
ep: 10000
ep_early: 1000
add_sl: True
adj_norm_1: True
adj_norm_2: False
nhid: 128
nhead: 1
wd: 5.0e-4
num_seed: 10
rnd: 123
is_normalize: False
cls_og: GNN
up_scale: 1